import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { api, type Application, type Project, type ProjectDetail, type User } from './api';
import { getApplicationPanelState } from './application-state';

type View = 'explore' | 'mine' | 'created' | 'profile';
type Feedback = { tone: 'success' | 'error' | 'info'; text: string } | null;

const statusText: Record<Application['status'], string> = {
  pending: '待审核', approved: '已通过', rejected: '已拒绝', withdrawn: '已撤回'
};

export function App() {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [feedback, setFeedback] = useState<Feedback>(null);

  useEffect(() => {
    api.me().then(({ user: current }) => setUser(current)).catch(() => undefined).finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="loading-screen"><span className="pulse-dot" />正在加载工作台</div>;
  if (!user) return <Login onLoggedIn={setUser} onError={setFeedback} feedback={feedback} />;
  return <Workspace user={user} onUserChange={setUser} onLogout={() => { void api.logout(); setUser(null); }} feedback={feedback} setFeedback={setFeedback} />;
}

function Login({ onLoggedIn, onError, feedback }: { onLoggedIn: (user: User) => void; onError: (feedback: Feedback) => void; feedback: Feedback }) {
  const [username, setUsername] = useState('bob');
  const [password, setPassword] = useState('demo1234');
  const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true); onError(null);
    try { onLoggedIn((await api.login(username, password)).user); }
    catch (error) { onError({ tone: 'error', text: error instanceof Error ? error.message : '登录失败' }); }
    finally { setBusy(false); }
  };
  return <main className="login-shell">
    <div className="login-visual"><div className="eyebrow">组队集市</div><h1 className="login-title"><span>找到适合你的</span><em>项目与队友</em></h1><p>浏览项目目标、招募角色和当前进展，选择一个你真正想参与的方向。</p><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="sticker">项目<br />协作<br /><strong>→</strong></div></div>
    <form className="login-card" onSubmit={submit}><div className="eyebrow">学生项目组队平台</div><h2>登录组队集市</h2><p className="muted">进入工作台，查看项目并管理申请</p><label>账号<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" /></label><label>密码<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="current-password" /></label>{feedback && <div className="inline-error">{feedback.text}</div>}<button className="primary" disabled={busy}>{busy ? '登录中…' : '登录并进入'} <span>↗</span></button><div className="account-hints"><small>测试账号：alice、bob、cathy、david</small><small>统一密码：demo1234</small></div></form>
  </main>;
}

function Workspace({ user, onUserChange, onLogout, feedback, setFeedback }: { user: User; onUserChange: (user: User) => void; onLogout: () => void; feedback: Feedback; setFeedback: (feedback: Feedback) => void }) {
  const [view, setView] = useState<View>('explore');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [refreshKey, setRefreshKey] = useState(0);
  const refresh = () => setRefreshKey((key) => key + 1);
  const navigate = (next: View) => { setView(next); setSelectedId(null); };
  return <div className="app-shell"><header className="topbar"><button className="brand" onClick={() => navigate('explore')}><span className="brand-mark">✳</span><span>组队集市<small>学生项目协作</small></span></button><nav><NavButton active={view === 'explore'} onClick={() => navigate('explore')}>发现项目</NavButton><NavButton active={view === 'mine'} onClick={() => navigate('mine')}>我的申请</NavButton><NavButton active={view === 'created'} onClick={() => navigate('created')}>我发起的</NavButton></nav><div className="user-menu"><span className="avatar">{user.nickname.slice(0, 1)}</span><span className="user-name">{user.nickname}<small>@{user.username}</small></span><button className="logout" onClick={onLogout}>退出</button></div></header><div className="page-wrap">{feedback && <div className={`feedback ${feedback.tone}`} role="alert"><span>{feedback.tone === 'error' ? '!' : '✓'}</span>{feedback.text}<button onClick={() => setFeedback(null)}>×</button></div>}{view === 'explore' && !selectedId && <Explore onSelect={setSelectedId} onFeedback={setFeedback} refreshKey={refreshKey} />}{view === 'explore' && selectedId && <ProjectPage id={selectedId} user={user} onBack={() => setSelectedId(null)} onFeedback={setFeedback} refresh={refresh} />}{view === 'mine' && <MyApplications onBack={() => navigate('explore')} onFeedback={setFeedback} refreshKey={refreshKey} />}{view === 'created' && !selectedId && <CreatedProjects user={user} onBack={() => navigate('explore')} onSelect={setSelectedId} onFeedback={setFeedback} refreshKey={refreshKey} onRefresh={refresh} />}{view === 'created' && selectedId && <ProjectPage id={selectedId} user={user} onBack={() => setSelectedId(null)} onFeedback={setFeedback} refresh={refresh} />}{view === 'profile' && <ProfilePage user={user} onBack={() => navigate('explore')} onUserChange={onUserChange} onFeedback={setFeedback} />}</div><button className="profile-fab" onClick={() => navigate('profile')}>编辑资料 <span>↗</span></button></div>;
}

function NavButton({ active, children, onClick }: { active: boolean; children: ReactNode; onClick: () => void }) { return <button className={active ? 'nav-link active' : 'nav-link'} onClick={onClick}>{children}</button>; }
function PageBack({ onBack, label = '返回发现项目' }: { onBack: () => void; label?: string }) { return <button className="page-back" onClick={onBack}><span>←</span>{label}</button>; }

function Explore({ onSelect, onFeedback, refreshKey }: { onSelect: (id: string) => void; onFeedback: (feedback: Feedback) => void; refreshKey: number }) {
  const [projects, setProjects] = useState<Project[]>([]); const [busy, setBusy] = useState(true); const [keyword, setKeyword] = useState(''); const [role, setRole] = useState(''); const [skills, setSkills] = useState('');
  const load = () => { setBusy(true); api.projects({ keyword, role, skills: skills.split(',').map((skill) => skill.trim()).filter(Boolean) }).then(({ projects: next }) => setProjects(next)).catch((error) => onFeedback({ tone: 'error', text: error instanceof Error ? error.message : '项目加载失败' })).finally(() => setBusy(false)); };
  useEffect(load, [refreshKey]);
  const openCount = projects.filter((project) => !project.recruitmentPaused && !project.allRolesFull).length;
  return <section><div className="hero-row"><div><div className="eyebrow">发现项目</div><h1 className="page-title">找到值得一起做的事</h1><p className="lead">查看项目目标、招募角色和当前进展，选择你能贡献的方向。</p></div><div className="hero-note"><span className="hero-note-arrow">↘</span><strong className="hero-note-count">{busy ? '—' : openCount}</strong><span className="hero-note-label">个项目<br />正在招募队友</span></div></div><div className="filter-bar"><div className="search-field"><span>⌕</span><input value={keyword} onChange={(event) => setKeyword(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && load()} placeholder="搜索项目名称或目标" /></div><input value={role} onChange={(event) => setRole(event.target.value)} placeholder="招募角色" /><input value={skills} onChange={(event) => setSkills(event.target.value)} placeholder="技能标签（逗号分隔）" /><button className="filter-button" onClick={load}>筛选项目 <span>↗</span></button></div>{busy ? <LoadingBlock /> : projects.length === 0 ? <EmptyState title="还没有匹配项目" text="换个关键词，或者稍后再来看看。" /> : <div className="project-grid">{projects.map((project, index) => <ProjectCard key={project.id} project={project} index={index} onClick={() => onSelect(project.id)} />)}</div>}<p className="seed-hint">测试素材仅用于验收：alice、bob、cathy、david</p></section>;
}

function ProjectCard({ project, index, onClick }: { project: Project; index: number; onClick: () => void }) { const accent = ['coral', 'blue', 'yellow'][index % 3]; return <article className={`project-card ${accent}`} onClick={onClick}><div className="card-top"><span className="project-index">项目 {String(index + 1).padStart(2, '0')}</span><span className={project.recruitmentPaused ? 'status paused' : project.allRolesFull ? 'status full' : 'status open'}>{project.recruitmentPaused ? '暂停招募' : project.allRolesFull ? '名额已满' : '正在招募'}</span></div><h3>{project.title}</h3><p>{project.goal}</p><div className="role-list">{project.roles.map((role) => <span key={role.id} className={role.remaining ? '' : 'role-full'}>{role.name}<b>{role.remaining ? `还缺 ${role.remaining} 人` : '名额已满'}</b></span>)}</div><div className="card-footer"><span>发起人：{project.owner.nickname}</span><span className="arrow">查看项目 ↗</span></div></article>; }

function ProjectPage({ id, user, onBack, onFeedback, refresh }: { id: string; user: User; onBack: () => void; onFeedback: (feedback: Feedback) => void; refresh: () => void }) {
  const [project, setProject] = useState<ProjectDetail | null>(null); const [busy, setBusy] = useState(true); const [projectError, setProjectError] = useState<string | null>(null); const [recruitmentBusy, setRecruitmentBusy] = useState(false);
  const load = () => { setBusy(true); setProjectError(null); api.project(id).then(({ project: next }) => setProject(next)).catch((error) => { const message = error instanceof Error ? error.message : '项目加载失败'; setProjectError(message); onFeedback({ tone: 'error', text: message }); }).finally(() => setBusy(false)); };
  useEffect(load, [id]);
  if (busy) return <><PageBack onBack={onBack} label="返回项目列表" /><LoadingBlock /></>;
  if (projectError || !project) return <><PageBack onBack={onBack} label="返回项目列表" /><div className="empty-state"><span>!</span><h3>项目加载失败</h3><p>{projectError ?? '项目不存在或暂时无法访问。'}</p><button className="outline-button" onClick={load}>重新加载</button></div></>;
  const owner = project.ownerId === user.id;
  const toggleRecruitment = async () => { setRecruitmentBusy(true); try { await api.setPaused(project.id, !project.recruitmentPaused); onFeedback({ tone: 'success', text: project.recruitmentPaused ? '招募已恢复。' : '招募已暂停，已有申请仍可审核。' }); load(); refresh(); } catch (error) { onFeedback({ tone: 'error', text: error instanceof Error ? error.message : '状态更新失败' }); } finally { setRecruitmentBusy(false); } };
  return <section><PageBack onBack={onBack} label="返回项目列表" /><div className="detail-head"><div><div className="eyebrow">项目详情</div><div className="detail-title-row"><h1 className="page-title small">{project.title}</h1><span className={project.recruitmentPaused ? 'status paused' : project.allRolesFull ? 'status full' : 'status open'}>{project.recruitmentPaused ? '暂停招募' : project.allRolesFull ? '招募已满' : '正在招募'}</span></div><p className="lead wide">{project.goal}</p></div>{owner && <button className="outline-button" disabled={recruitmentBusy} onClick={toggleRecruitment}>{recruitmentBusy ? '更新中…' : project.recruitmentPaused ? '恢复招募' : '暂停招募'} <span>↗</span></button>}</div><div className="detail-layout"><div className="detail-main"><InfoPanel title="项目概览"><div className="story-grid"><Story label="当前进展" text={project.progress} /><Story label="预期成果" text={project.expectedOutcome} /></div></InfoPanel><InfoPanel title="招募角色"><div className="role-detail-list">{project.roles.map((role) => <div className="role-detail" key={role.id}><div><strong>{role.name}</strong><span>需要技能：{role.skills.join('、')}</span></div><div className="capacity"><b>{role.remaining}</b> / {role.capacity}<small>剩余名额</small></div></div>)}</div></InfoPanel><InfoPanel title={`团队成员 · ${project.memberCount}`}><div className="member-row">{project.members.map((member) => <div className="member" key={member.id}><span className="member-avatar">{member.user.nickname.slice(0, 1)}</span><span>{member.user.nickname}<small>{member.isOwner ? '项目发起人' : project.roles.find((role) => role.id === member.roleId)?.name ?? '成员'}</small></span></div>)}</div></InfoPanel></div><aside className="detail-aside"><div className="owner-card"><div className="eyebrow">项目发起人</div><div className="owner-avatar">{project.owner.nickname.slice(0, 1)}</div><h3>{project.owner.nickname}</h3><p>{project.ownerProfile.bio}</p><div className="tag-list">{project.ownerProfile.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><small>每周可投入：{project.ownerProfile.weeklyHours} 小时</small></div>{owner ? <ReviewPanel project={project} onFeedback={onFeedback} refresh={load} /> : <ApplicationForm project={project} user={user} onFeedback={onFeedback} onDone={load} />}</aside></div></section>;
}

function InfoPanel({ title, children }: { title: string; children: ReactNode }) { return <div className="info-panel"><div className="panel-heading"><h2>{title}</h2><span>✳</span></div>{children}</div>; }
function Story({ label, text }: { label: string; text: string }) { return <div className="story"><span>{label}</span><p>{text}</p></div>; }

function ApplicationForm({ project, user, onFeedback, onDone }: { project: ProjectDetail; user: User; onFeedback: (feedback: Feedback) => void; onDone: () => void }) {
  const applicationState = getApplicationPanelState(project.applications, user.id);
  const [roleId, setRoleId] = useState(project.roles.find((role) => role.remaining)?.id ?? ''); const [reason, setReason] = useState(''); const [contribution, setContribution] = useState(''); const [busy, setBusy] = useState(false); const disabled = project.recruitmentPaused || project.allRolesFull || !project.roles.some((role) => role.remaining);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await api.createApplication(project.id, { roleId, reason, contribution }); onFeedback({ tone: 'success', text: '申请已提交，等待发起人审核。' }); setReason(''); setContribution(''); onDone(); } catch (error) { onFeedback({ tone: 'error', text: error instanceof Error ? error.message : '申请提交失败' }); } finally { setBusy(false); } };
  return <div className="apply-card"><div className="eyebrow">申请加入</div><h2>选择一个角色<br /><em>开始贡献</em></h2>{applicationState.kind === 'approved' ? <div className="blocked-note">你已经是本项目成员，角色：{project.roles.find((role) => role.id === applicationState.roleId)?.name ?? '已加入'}。</div> : applicationState.kind === 'pending' ? <div className="blocked-note">你已提交待审核申请，发起人审核后会在“我的申请”显示结果。</div> : disabled ? <div className="blocked-note">{project.recruitmentPaused ? '项目已暂停招募，暂不接受新申请。' : '当前没有可申请的角色。'}</div> : <form onSubmit={submit}><label>申请角色<select value={roleId} onChange={(event) => setRoleId(event.target.value)}>{project.roles.filter((role) => role.remaining).map((role) => <option key={role.id} value={role.id}>{role.name} · 还缺 {role.remaining} 人</option>)}</select></label><label>为什么想加入？<textarea required maxLength={2000} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="介绍你的相关经历和参与动机" /></label><label>你可以承担什么？<textarea required maxLength={2000} value={contribution} onChange={(event) => setContribution(event.target.value)} placeholder="描述你愿意负责的具体内容" /></label><button className="primary" disabled={busy}>{busy ? '提交中…' : '提交申请'} <span>↗</span></button></form>}</div>;
}

function ReviewPanel({ project, onFeedback, refresh }: { project: ProjectDetail; onFeedback: (feedback: Feedback) => void; refresh: () => void }) {
  const pending = project.applications.filter((application) => application.status === 'pending'); const [busyId, setBusyId] = useState<string | null>(null);
  const decide = async (application: Application, action: 'approve' | 'reject') => { if (busyId) return; try { let rejectionReason = ''; if (action === 'reject') { const reason = window.prompt('请输入拒绝原因：', '当前角色匹配度暂不合适'); if (!reason) return; rejectionReason = reason; } setBusyId(application.id); if (action === 'approve') await api.approve(application.id); else await api.reject(application.id, rejectionReason); onFeedback({ tone: 'success', text: action === 'approve' ? '申请已通过，成员和名额已同步更新。' : '申请已拒绝，申请人可以查看原因并重新申请。' }); refresh(); } catch (error) { onFeedback({ tone: 'error', text: error instanceof Error ? error.message : '审核失败' }); } finally { setBusyId(null); } };
  return <div className="review-card"><div className="panel-heading"><h2>申请审核</h2><span>{pending.length} 条待处理</span></div>{project.applications.length === 0 ? <EmptyState title="还没有申请" text="新的申请会出现在这里。" /> : <div className="application-list">{project.applications.map((application) => <div className="application-item" key={application.id}><div className="application-meta"><span className="member-avatar">{application.profileSnapshot.nickname.slice(0, 1)}</span><div><strong>{application.profileSnapshot.nickname}</strong><small>{project.roles.find((role) => role.id === application.roleId)?.name} · {statusText[application.status]}</small></div></div><div className="snapshot-details"><p>{application.profileSnapshot.bio}</p><span>技能：{application.profileSnapshot.skills.join('、')}</span><span>每周可投入：{application.profileSnapshot.weeklyHours} 小时</span></div><p>申请理由：{application.reason}</p><small className="contribution">可承担：{application.contribution}</small>{application.status === 'pending' ? <div className="review-actions"><button className="approve-button" disabled={busyId === application.id} onClick={() => decide(application, 'approve')}>{busyId === application.id ? '处理中…' : '接受申请'}</button><button className="reject-button" disabled={busyId === application.id} onClick={() => decide(application, 'reject')}>拒绝申请</button></div> : application.rejectionReason ? <div className="rejection-reason">拒绝原因：{application.rejectionReason}</div> : null}</div>)}</div>}</div>;
}

function MyApplications({ onBack, onFeedback, refreshKey }: { onBack: () => void; onFeedback: (feedback: Feedback) => void; refreshKey: number }) {
  const [applications, setApplications] = useState<Application[]>([]); const [busy, setBusy] = useState(true); const [withdrawingId, setWithdrawingId] = useState<string | null>(null);
  useEffect(() => { setBusy(true); api.applications().then(({ applications: next }) => setApplications(next)).catch((error) => onFeedback({ tone: 'error', text: error instanceof Error ? error.message : '申请加载失败' })).finally(() => setBusy(false)); }, [refreshKey]);
  const withdraw = async (application: Application) => { setWithdrawingId(application.id); try { await api.withdraw(application.id); onFeedback({ tone: 'success', text: '申请已撤回，之后仍可重新申请。' }); setApplications((items) => items.map((item) => item.id === application.id ? { ...item, status: 'withdrawn' } : item)); } catch (error) { onFeedback({ tone: 'error', text: error instanceof Error ? error.message : '撤回失败' }); } finally { setWithdrawingId(null); } };
  return <section><PageBack onBack={onBack} /><div className="eyebrow">我的申请</div><h1 className="page-title">查看申请状态<br /><em>知道下一步做什么</em></h1><p className="lead">每条申请都会保留记录，审核结果和拒绝原因会显示在这里。</p>{busy ? <LoadingBlock /> : applications.length === 0 ? <EmptyState title="还没有申请记录" text="去发现项目，提交你的第一份申请吧。" /> : <div className="application-history">{applications.map((application) => <div className="history-row" key={application.id}><div><span className={`status-badge ${application.status}`}>{statusText[application.status]}</span><h3>{application.projectTitle ?? '项目申请'}</h3><p className="history-role">申请角色：{application.roleName ?? '待确认'}</p><p>{application.reason}</p>{application.rejectionReason && <small>拒绝原因：{application.rejectionReason}</small>}</div><div className="history-side"><span>{new Date(application.createdAt).toLocaleDateString('zh-CN')}</span>{application.status === 'pending' && <button className="text-button" disabled={withdrawingId === application.id} onClick={() => withdraw(application)}>{withdrawingId === application.id ? '撤回中…' : '撤回申请'}</button>}</div></div>)}</div>}<p className="section-footnote">待审核申请不会占用角色名额</p></section>;
}

function CreatedProjects({ user, onBack, onSelect, onFeedback, refreshKey, onRefresh }: { user: User; onBack: () => void; onSelect: (id: string) => void; onFeedback: (feedback: Feedback) => void; refreshKey: number; onRefresh: () => void }) {
  const [projects, setProjects] = useState<Project[]>([]); const [busy, setBusy] = useState(true);
  useEffect(() => { setBusy(true); api.projects({ ownedBy: user.id }).then(({ projects: next }) => setProjects(next)).catch((error) => onFeedback({ tone: 'error', text: error instanceof Error ? error.message : '项目加载失败' })).finally(() => setBusy(false)); }, [refreshKey, user.id]);
  return <section><PageBack onBack={onBack} /><div className="eyebrow">我发起的项目</div><div className="section-title-row"><h1 className="page-title">管理项目进展<br /><em>和团队申请</em></h1><button className="primary compact" onClick={() => window.dispatchEvent(new CustomEvent('new-project'))}>发布新项目 <span>↗</span></button></div><p className="lead">更新招募状态，查看申请资料，及时处理成员申请。</p>{busy ? <LoadingBlock /> : projects.length === 0 ? <EmptyState title="还没有发起项目" text="发布一个项目，开始寻找队友。" /> : <div className="project-grid">{projects.map((project, index) => <ProjectCard key={project.id} project={project} index={index} onClick={() => onSelect(project.id)} />)}</div>}<CreateProjectForm onFeedback={onFeedback} onDone={onRefresh} /></section>;
}

function CreateProjectForm({ onFeedback, onDone }: { onFeedback: (feedback: Feedback) => void; onDone: () => void }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [title, setTitle] = useState(''); const [goal, setGoal] = useState(''); const [progress, setProgress] = useState(''); const [outcome, setOutcome] = useState(''); const [roles, setRoles] = useState([{ name: '', skills: '', capacity: 1 }]);
  useEffect(() => { const openForm = () => setOpen(true); window.addEventListener('new-project', openForm); return () => window.removeEventListener('new-project', openForm); }, []);
  if (!open) return null;
  const updateRole = (index: number, patch: Partial<typeof roles[number]>) => setRoles((current) => current.map((role, i) => i === index ? { ...role, ...patch } : role));
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await api.createProject({ title, goal, progress, expectedOutcome: outcome, roles: roles.map((role) => ({ name: role.name.trim(), skills: role.skills.split(',').map((skill) => skill.trim()).filter(Boolean), capacity: role.capacity })) }); onFeedback({ tone: 'success', text: '项目已发布，可以开始接收申请。' }); setOpen(false); onDone(); setRoles([{ name: '', skills: '', capacity: 1 }]); } catch (error) { onFeedback({ tone: 'error', text: error instanceof Error ? error.message : '项目发布失败' }); } finally { setBusy(false); } };
  return <div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><button type="button" className="close-button" onClick={() => setOpen(false)}>×</button><div className="eyebrow">发布项目</div><h2>让一个想法<br /><em>找到队友</em></h2><div className="form-grid"><label className="wide-field">项目标题<input required maxLength={120} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="wide-field">项目目标<textarea required maxLength={3000} value={goal} onChange={(event) => setGoal(event.target.value)} /></label><label>当前进展<textarea required maxLength={3000} value={progress} onChange={(event) => setProgress(event.target.value)} /></label><label>预期成果<textarea required maxLength={3000} value={outcome} onChange={(event) => setOutcome(event.target.value)} /></label></div><div className="role-editor"><div className="panel-heading"><h3>招募角色</h3><button type="button" className="text-button" disabled={roles.length >= 30} onClick={() => setRoles((current) => [...current, { name: '', skills: '', capacity: 1 }])}>添加招募角色</button></div>{roles.map((role, index) => <div className="role-edit-row" key={index}><label>角色名称<input required maxLength={80} value={role.name} onChange={(event) => updateRole(index, { name: event.target.value })} /></label><label>技能要求<input required maxLength={1200} value={role.skills} onChange={(event) => updateRole(index, { skills: event.target.value })} placeholder="逗号分隔，例如 React、TypeScript" /></label><label>招募人数<input type="number" min="1" max="999" required value={role.capacity} onChange={(event) => updateRole(index, { capacity: Number(event.target.value) })} /></label>{roles.length > 1 && <button type="button" className="text-button" onClick={() => setRoles((current) => current.filter((_, i) => i !== index))}>删除角色</button>}</div>)}</div><button className="primary" disabled={busy}>{busy ? '发布中…' : '发布项目'} <span>↗</span></button></form></div>;
}

function ProfilePage({ user, onBack, onUserChange, onFeedback }: { user: User; onBack: () => void; onUserChange: (user: User) => void; onFeedback: (feedback: Feedback) => void }) {
  const [profile, setProfile] = useState(user); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { const result = await api.updateProfile({ nickname: profile.nickname, bio: profile.bio, skills: profile.skills, weeklyHours: profile.weeklyHours }); onUserChange(result.profile); onFeedback({ tone: 'success', text: '个人资料已更新。新申请会使用最新资料快照。' }); } catch (error) { onFeedback({ tone: 'error', text: error instanceof Error ? error.message : '资料更新失败' }); } finally { setBusy(false); } };
  return <section><PageBack onBack={onBack} /><div className="eyebrow">个人资料</div><h1 className="page-title">让队友了解你<br /><em>能带来什么</em></h1><p className="lead">完善技能和时间安排，帮助项目发起人判断是否适合一起合作。</p><form className="profile-form" onSubmit={submit}><label>昵称<input required value={profile.nickname} onChange={(event) => setProfile({ ...profile, nickname: event.target.value })} /></label><label>每周可投入小时<input type="number" min="0" max="168" value={profile.weeklyHours} onChange={(event) => setProfile({ ...profile, weeklyHours: Number(event.target.value) })} /></label><label className="wide-field">个人简介<textarea value={profile.bio} onChange={(event) => setProfile({ ...profile, bio: event.target.value })} placeholder="介绍你的经历和想参与的方向" /></label><label className="wide-field">技能标签<textarea value={profile.skills.join(', ')} onChange={(event) => setProfile({ ...profile, skills: event.target.value.split(',').map((skill) => skill.trim()).filter(Boolean) })} placeholder="例如：React、数据分析、用户研究" /></label><button className="primary" disabled={busy}>{busy ? '保存中…' : '保存资料'} <span>↗</span></button></form></section>;
}

function LoadingBlock() { return <div className="loading-block"><span className="pulse-dot" />正在加载…</div>; }
function EmptyState({ title, text }: { title: string; text: string }) { return <div className="empty-state"><span>⌁</span><h3>{title}</h3><p>{text}</p></div>; }
